"""sar2 table

Revision ID: 905e6ce7fe3d
Revises: 93b00a9206cc
Create Date: 2018-05-28 19:13:24.251352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905e6ce7fe3d'
down_revision = '93b00a9206cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaver', sa.Column('track_detail', sa.String(length=1000), nullable=True))
    op.add_column('leaver', sa.Column('track_lst_update', sa.DateTime(), nullable=True))
    op.add_column('leaver', sa.Column('track_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaver', 'track_name')
    op.drop_column('leaver', 'track_lst_update')
    op.drop_column('leaver', 'track_detail')
    # ### end Alembic commands ###
