"""sar2 table

Revision ID: dc7d6aa28dd0
Revises: 
Create Date: 2018-04-29 17:13:24.538688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7d6aa28dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('repemail', sa.String(length=100), nullable=True),
    sa.Column('repcode', sa.String(length=10), nullable=True),
    sa.Column('teamcode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repcode')
    )
    op.create_table('leaver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prole', sa.String(length=100), nullable=True),
    sa.Column('pfirm', sa.String(length=100), nullable=True),
    sa.Column('lrole', sa.String(length=100), nullable=True),
    sa.Column('lfirm', sa.String(length=100), nullable=True),
    sa.Column('llink', sa.String(length=100), nullable=True),
    sa.Column('llocation', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=10), nullable=True),
    sa.Column('repcode', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repcode'], ['srep.repcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaver_timestamp'), 'leaver', ['timestamp'], unique=False)
    op.create_table('suspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaverid', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('include', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('firm', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=75), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leaverid'], ['leaver.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_suspect_timestamp'), 'suspect', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspect_timestamp'), table_name='suspect')
    op.drop_table('suspect')
    op.drop_index(op.f('ix_leaver_timestamp'), table_name='leaver')
    op.drop_table('leaver')
    op.drop_table('srep')
    # ### end Alembic commands ###
