"""sar table

Revision ID: f1fd9c08a764
Revises: db576221c5d0
Create Date: 2018-05-02 22:32:28.345085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fd9c08a764'
down_revision = 'db576221c5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('firm', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=10), nullable=True),
    sa.Column('repcode', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('srepid', sa.Integer(), nullable=True),
    sa.Column('leaverid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leaverid'], ['leaver.id'], ),
    sa.ForeignKeyConstraint(['repcode'], ['srep.repcode'], ),
    sa.ForeignKeyConstraint(['srepid'], ['srep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescue_timestamp'), 'rescue', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rescue_timestamp'), table_name='rescue')
    op.drop_table('rescue')
    # ### end Alembic commands ###
